#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employee
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="admission")]
	public partial class EmpDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmission(admission instance);
    partial void Updateadmission(admission instance);
    partial void Deleteadmission(admission instance);
    partial void Insertstate(state instance);
    partial void Updatestate(state instance);
    partial void Deletestate(state instance);
    partial void InsertbloodGroup(bloodGroup instance);
    partial void UpdatebloodGroup(bloodGroup instance);
    partial void DeletebloodGroup(bloodGroup instance);
    partial void Insertcatogery(catogery instance);
    partial void Updatecatogery(catogery instance);
    partial void Deletecatogery(catogery instance);
    partial void Insertcity(city instance);
    partial void Updatecity(city instance);
    partial void Deletecity(city instance);
    partial void Insertclass(@class instance);
    partial void Updateclass(@class instance);
    partial void Deleteclass(@class instance);
    partial void Insertgender(gender instance);
    partial void Updategender(gender instance);
    partial void Deletegender(gender instance);
    partial void Insertnationality(nationality instance);
    partial void Updatenationality(nationality instance);
    partial void Deletenationality(nationality instance);
    partial void Insertsection(section instance);
    partial void Updatesection(section instance);
    partial void Deletesection(section instance);
    partial void Insertsession(session instance);
    partial void Updatesession(session instance);
    partial void Deletesession(session instance);
    #endregion
		
		public EmpDataDataContext() : 
				base(global::employee.Properties.Settings.Default.admissionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admission> admissions
		{
			get
			{
				return this.GetTable<admission>();
			}
		}
		
		public System.Data.Linq.Table<state> states
		{
			get
			{
				return this.GetTable<state>();
			}
		}
		
		public System.Data.Linq.Table<bloodGroup> bloodGroups
		{
			get
			{
				return this.GetTable<bloodGroup>();
			}
		}
		
		public System.Data.Linq.Table<catogery> catogeries
		{
			get
			{
				return this.GetTable<catogery>();
			}
		}
		
		public System.Data.Linq.Table<city> cities
		{
			get
			{
				return this.GetTable<city>();
			}
		}
		
		public System.Data.Linq.Table<@class> classes
		{
			get
			{
				return this.GetTable<@class>();
			}
		}
		
		public System.Data.Linq.Table<gender> genders
		{
			get
			{
				return this.GetTable<gender>();
			}
		}
		
		public System.Data.Linq.Table<nationality> nationalities
		{
			get
			{
				return this.GetTable<nationality>();
			}
		}
		
		public System.Data.Linq.Table<section> sections
		{
			get
			{
				return this.GetTable<section>();
			}
		}
		
		public System.Data.Linq.Table<session> sessions
		{
			get
			{
				return this.GetTable<session>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admission")]
	public partial class admission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admissionId;
		
		private string _admissionNo;
		
		private string _studentName;
		
		private System.DateTime _DOB;
		
		private string _addharNo;
		
		private string _Email;
		
		private string _mobileNo;
		
		private int _GenderId;
		
		private int _bloodGroup;
		
		private int _nationality;
		
		private int _sessionId;
		
		private int _sectionId;
		
		private int _categoryId;
		
		private int _stateId;
		
		private int _cityId;
		
		private string _fatherName;
		
		private string _motherName;
		
		private string _fatherOccupation;
		
		private string _fatherMobileNo;
		
		private byte _status;
		
		private EntityRef<state> _state;
		
		private EntityRef<bloodGroup> _bloodGroup1;
		
		private EntityRef<catogery> _catogery;
		
		private EntityRef<city> _city;
		
		private EntityRef<gender> _gender;
		
		private EntityRef<nationality> _nationality1;
		
		private EntityRef<section> _section;
		
		private EntityRef<session> _session;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadmissionIdChanging(int value);
    partial void OnadmissionIdChanged();
    partial void OnadmissionNoChanging(string value);
    partial void OnadmissionNoChanged();
    partial void OnstudentNameChanging(string value);
    partial void OnstudentNameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnaddharNoChanging(string value);
    partial void OnaddharNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnmobileNoChanging(string value);
    partial void OnmobileNoChanged();
    partial void OnGenderIdChanging(int value);
    partial void OnGenderIdChanged();
    partial void OnbloodGroupChanging(int value);
    partial void OnbloodGroupChanged();
    partial void OnnationalityChanging(int value);
    partial void OnnationalityChanged();
    partial void OnsessionIdChanging(int value);
    partial void OnsessionIdChanged();
    partial void OnsectionIdChanging(int value);
    partial void OnsectionIdChanged();
    partial void OncategoryIdChanging(int value);
    partial void OncategoryIdChanged();
    partial void OnstateIdChanging(int value);
    partial void OnstateIdChanged();
    partial void OncityIdChanging(int value);
    partial void OncityIdChanged();
    partial void OnfatherNameChanging(string value);
    partial void OnfatherNameChanged();
    partial void OnmotherNameChanging(string value);
    partial void OnmotherNameChanged();
    partial void OnfatherOccupationChanging(string value);
    partial void OnfatherOccupationChanged();
    partial void OnfatherMobileNoChanging(string value);
    partial void OnfatherMobileNoChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public admission()
		{
			this._state = default(EntityRef<state>);
			this._bloodGroup1 = default(EntityRef<bloodGroup>);
			this._catogery = default(EntityRef<catogery>);
			this._city = default(EntityRef<city>);
			this._gender = default(EntityRef<gender>);
			this._nationality1 = default(EntityRef<nationality>);
			this._section = default(EntityRef<section>);
			this._session = default(EntityRef<session>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admissionId
		{
			get
			{
				return this._admissionId;
			}
			set
			{
				if ((this._admissionId != value))
				{
					this.OnadmissionIdChanging(value);
					this.SendPropertyChanging();
					this._admissionId = value;
					this.SendPropertyChanged("admissionId");
					this.OnadmissionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissionNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string admissionNo
		{
			get
			{
				return this._admissionNo;
			}
			set
			{
				if ((this._admissionNo != value))
				{
					this.OnadmissionNoChanging(value);
					this.SendPropertyChanging();
					this._admissionNo = value;
					this.SendPropertyChanged("admissionNo");
					this.OnadmissionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string studentName
		{
			get
			{
				return this._studentName;
			}
			set
			{
				if ((this._studentName != value))
				{
					this.OnstudentNameChanging(value);
					this.SendPropertyChanging();
					this._studentName = value;
					this.SendPropertyChanged("studentName");
					this.OnstudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addharNo", DbType="VarChar(12)")]
		public string addharNo
		{
			get
			{
				return this._addharNo;
			}
			set
			{
				if ((this._addharNo != value))
				{
					this.OnaddharNoChanging(value);
					this.SendPropertyChanging();
					this._addharNo = value;
					this.SendPropertyChanged("addharNo");
					this.OnaddharNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobileNo", DbType="VarChar(15)")]
		public string mobileNo
		{
			get
			{
				return this._mobileNo;
			}
			set
			{
				if ((this._mobileNo != value))
				{
					this.OnmobileNoChanging(value);
					this.SendPropertyChanging();
					this._mobileNo = value;
					this.SendPropertyChanged("mobileNo");
					this.OnmobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderId", DbType="Int NOT NULL")]
		public int GenderId
		{
			get
			{
				return this._GenderId;
			}
			set
			{
				if ((this._GenderId != value))
				{
					if (this._gender.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGenderIdChanging(value);
					this.SendPropertyChanging();
					this._GenderId = value;
					this.SendPropertyChanged("GenderId");
					this.OnGenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloodGroup", DbType="Int NOT NULL")]
		public int bloodGroup
		{
			get
			{
				return this._bloodGroup;
			}
			set
			{
				if ((this._bloodGroup != value))
				{
					if (this._bloodGroup1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbloodGroupChanging(value);
					this.SendPropertyChanging();
					this._bloodGroup = value;
					this.SendPropertyChanged("bloodGroup");
					this.OnbloodGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="Int NOT NULL")]
		public int nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					if (this._nationality1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnationalityChanging(value);
					this.SendPropertyChanging();
					this._nationality = value;
					this.SendPropertyChanged("nationality");
					this.OnnationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionId", DbType="Int NOT NULL")]
		public int sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				if ((this._sessionId != value))
				{
					if (this._session.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsessionIdChanging(value);
					this.SendPropertyChanging();
					this._sessionId = value;
					this.SendPropertyChanged("sessionId");
					this.OnsessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionId", DbType="Int NOT NULL")]
		public int sectionId
		{
			get
			{
				return this._sectionId;
			}
			set
			{
				if ((this._sectionId != value))
				{
					if (this._section.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsectionIdChanging(value);
					this.SendPropertyChanging();
					this._sectionId = value;
					this.SendPropertyChanged("sectionId");
					this.OnsectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryId", DbType="Int NOT NULL")]
		public int categoryId
		{
			get
			{
				return this._categoryId;
			}
			set
			{
				if ((this._categoryId != value))
				{
					if (this._catogery.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategoryIdChanging(value);
					this.SendPropertyChanging();
					this._categoryId = value;
					this.SendPropertyChanged("categoryId");
					this.OncategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", DbType="Int NOT NULL")]
		public int stateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				if ((this._stateId != value))
				{
					if (this._state.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstateIdChanging(value);
					this.SendPropertyChanging();
					this._stateId = value;
					this.SendPropertyChanged("stateId");
					this.OnstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityId", DbType="Int NOT NULL")]
		public int cityId
		{
			get
			{
				return this._cityId;
			}
			set
			{
				if ((this._cityId != value))
				{
					if (this._city.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncityIdChanging(value);
					this.SendPropertyChanging();
					this._cityId = value;
					this.SendPropertyChanged("cityId");
					this.OncityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fatherName", DbType="VarChar(100)")]
		public string fatherName
		{
			get
			{
				return this._fatherName;
			}
			set
			{
				if ((this._fatherName != value))
				{
					this.OnfatherNameChanging(value);
					this.SendPropertyChanging();
					this._fatherName = value;
					this.SendPropertyChanged("fatherName");
					this.OnfatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motherName", DbType="VarChar(100)")]
		public string motherName
		{
			get
			{
				return this._motherName;
			}
			set
			{
				if ((this._motherName != value))
				{
					this.OnmotherNameChanging(value);
					this.SendPropertyChanging();
					this._motherName = value;
					this.SendPropertyChanged("motherName");
					this.OnmotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fatherOccupation", DbType="VarChar(100)")]
		public string fatherOccupation
		{
			get
			{
				return this._fatherOccupation;
			}
			set
			{
				if ((this._fatherOccupation != value))
				{
					this.OnfatherOccupationChanging(value);
					this.SendPropertyChanging();
					this._fatherOccupation = value;
					this.SendPropertyChanged("fatherOccupation");
					this.OnfatherOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fatherMobileNo", DbType="VarChar(15)")]
		public string fatherMobileNo
		{
			get
			{
				return this._fatherMobileNo;
			}
			set
			{
				if ((this._fatherMobileNo != value))
				{
					this.OnfatherMobileNoChanging(value);
					this.SendPropertyChanging();
					this._fatherMobileNo = value;
					this.SendPropertyChanged("fatherMobileNo");
					this.OnfatherMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_admission", Storage="_state", ThisKey="stateId", OtherKey="stateId", IsForeignKey=true)]
		public state state
		{
			get
			{
				return this._state.Entity;
			}
			set
			{
				state previousValue = this._state.Entity;
				if (((previousValue != value) 
							|| (this._state.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._state.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._state.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._stateId = value.stateId;
					}
					else
					{
						this._stateId = default(int);
					}
					this.SendPropertyChanged("state");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bloodGroup_admission", Storage="_bloodGroup1", ThisKey="bloodGroup", OtherKey="bloodId", IsForeignKey=true)]
		public bloodGroup bloodGroup1
		{
			get
			{
				return this._bloodGroup1.Entity;
			}
			set
			{
				bloodGroup previousValue = this._bloodGroup1.Entity;
				if (((previousValue != value) 
							|| (this._bloodGroup1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bloodGroup1.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._bloodGroup1.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._bloodGroup = value.bloodId;
					}
					else
					{
						this._bloodGroup = default(int);
					}
					this.SendPropertyChanged("bloodGroup1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="catogery_admission", Storage="_catogery", ThisKey="categoryId", OtherKey="catogeryId", IsForeignKey=true)]
		public catogery catogery
		{
			get
			{
				return this._catogery.Entity;
			}
			set
			{
				catogery previousValue = this._catogery.Entity;
				if (((previousValue != value) 
							|| (this._catogery.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._catogery.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._catogery.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._categoryId = value.catogeryId;
					}
					else
					{
						this._categoryId = default(int);
					}
					this.SendPropertyChanged("catogery");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="city_admission", Storage="_city", ThisKey="cityId", OtherKey="cityId", IsForeignKey=true)]
		public city city
		{
			get
			{
				return this._city.Entity;
			}
			set
			{
				city previousValue = this._city.Entity;
				if (((previousValue != value) 
							|| (this._city.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._city.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._city.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._cityId = value.cityId;
					}
					else
					{
						this._cityId = default(int);
					}
					this.SendPropertyChanged("city");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gender_admission", Storage="_gender", ThisKey="GenderId", OtherKey="genderId", IsForeignKey=true)]
		public gender gender
		{
			get
			{
				return this._gender.Entity;
			}
			set
			{
				gender previousValue = this._gender.Entity;
				if (((previousValue != value) 
							|| (this._gender.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gender.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._gender.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._GenderId = value.genderId;
					}
					else
					{
						this._GenderId = default(int);
					}
					this.SendPropertyChanged("gender");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nationality_admission", Storage="_nationality1", ThisKey="nationality", OtherKey="nationalityId", IsForeignKey=true)]
		public nationality nationality1
		{
			get
			{
				return this._nationality1.Entity;
			}
			set
			{
				nationality previousValue = this._nationality1.Entity;
				if (((previousValue != value) 
							|| (this._nationality1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nationality1.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._nationality1.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._nationality = value.nationalityId;
					}
					else
					{
						this._nationality = default(int);
					}
					this.SendPropertyChanged("nationality1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="section_admission", Storage="_section", ThisKey="sectionId", OtherKey="sectionId", IsForeignKey=true)]
		public section section
		{
			get
			{
				return this._section.Entity;
			}
			set
			{
				section previousValue = this._section.Entity;
				if (((previousValue != value) 
							|| (this._section.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._section.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._section.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._sectionId = value.sectionId;
					}
					else
					{
						this._sectionId = default(int);
					}
					this.SendPropertyChanged("section");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="session_admission", Storage="_session", ThisKey="sessionId", OtherKey="sessionId", IsForeignKey=true)]
		public session session
		{
			get
			{
				return this._session.Entity;
			}
			set
			{
				session previousValue = this._session.Entity;
				if (((previousValue != value) 
							|| (this._session.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._session.Entity = null;
						previousValue.admissions.Remove(this);
					}
					this._session.Entity = value;
					if ((value != null))
					{
						value.admissions.Add(this);
						this._sessionId = value.sessionId;
					}
					else
					{
						this._sessionId = default(int);
					}
					this.SendPropertyChanged("session");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.state")]
	public partial class state : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stateId;
		
		private string _stateName;
		
		private string _stateCode;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
		private EntitySet<city> _cities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstateIdChanging(int value);
    partial void OnstateIdChanged();
    partial void OnstateNameChanging(string value);
    partial void OnstateNameChanged();
    partial void OnstateCodeChanging(string value);
    partial void OnstateCodeChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public state()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			this._cities = new EntitySet<city>(new Action<city>(this.attach_cities), new Action<city>(this.detach_cities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				if ((this._stateId != value))
				{
					this.OnstateIdChanging(value);
					this.SendPropertyChanging();
					this._stateId = value;
					this.SendPropertyChanged("stateId");
					this.OnstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string stateName
		{
			get
			{
				return this._stateName;
			}
			set
			{
				if ((this._stateName != value))
				{
					this.OnstateNameChanging(value);
					this.SendPropertyChanging();
					this._stateName = value;
					this.SendPropertyChanged("stateName");
					this.OnstateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string stateCode
		{
			get
			{
				return this._stateCode;
			}
			set
			{
				if ((this._stateCode != value))
				{
					this.OnstateCodeChanging(value);
					this.SendPropertyChanging();
					this._stateCode = value;
					this.SendPropertyChanged("stateCode");
					this.OnstateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_admission", Storage="_admissions", ThisKey="stateId", OtherKey="stateId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_city", Storage="_cities", ThisKey="stateId", OtherKey="stateId")]
		public EntitySet<city> cities
		{
			get
			{
				return this._cities;
			}
			set
			{
				this._cities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.state = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.state = null;
		}
		
		private void attach_cities(city entity)
		{
			this.SendPropertyChanging();
			entity.state = this;
		}
		
		private void detach_cities(city entity)
		{
			this.SendPropertyChanging();
			entity.state = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bloodGroup")]
	public partial class bloodGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bloodId;
		
		private string _bloodName;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbloodIdChanging(int value);
    partial void OnbloodIdChanged();
    partial void OnbloodNameChanging(string value);
    partial void OnbloodNameChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public bloodGroup()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloodId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int bloodId
		{
			get
			{
				return this._bloodId;
			}
			set
			{
				if ((this._bloodId != value))
				{
					this.OnbloodIdChanging(value);
					this.SendPropertyChanging();
					this._bloodId = value;
					this.SendPropertyChanged("bloodId");
					this.OnbloodIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloodName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string bloodName
		{
			get
			{
				return this._bloodName;
			}
			set
			{
				if ((this._bloodName != value))
				{
					this.OnbloodNameChanging(value);
					this.SendPropertyChanging();
					this._bloodName = value;
					this.SendPropertyChanged("bloodName");
					this.OnbloodNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bloodGroup_admission", Storage="_admissions", ThisKey="bloodId", OtherKey="bloodGroup")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.bloodGroup1 = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.bloodGroup1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.catogery")]
	public partial class catogery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _catogeryId;
		
		private string _catogeryName;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncatogeryIdChanging(int value);
    partial void OncatogeryIdChanged();
    partial void OncatogeryNameChanging(string value);
    partial void OncatogeryNameChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public catogery()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catogeryId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int catogeryId
		{
			get
			{
				return this._catogeryId;
			}
			set
			{
				if ((this._catogeryId != value))
				{
					this.OncatogeryIdChanging(value);
					this.SendPropertyChanging();
					this._catogeryId = value;
					this.SendPropertyChanged("catogeryId");
					this.OncatogeryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catogeryName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string catogeryName
		{
			get
			{
				return this._catogeryName;
			}
			set
			{
				if ((this._catogeryName != value))
				{
					this.OncatogeryNameChanging(value);
					this.SendPropertyChanging();
					this._catogeryName = value;
					this.SendPropertyChanged("catogeryName");
					this.OncatogeryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="catogery_admission", Storage="_admissions", ThisKey="catogeryId", OtherKey="categoryId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.catogery = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.catogery = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.city")]
	public partial class city : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cityId;
		
		private string _cityName;
		
		private int _stateId;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
		private EntityRef<state> _state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncityIdChanging(int value);
    partial void OncityIdChanged();
    partial void OncityNameChanging(string value);
    partial void OncityNameChanged();
    partial void OnstateIdChanging(int value);
    partial void OnstateIdChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public city()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			this._state = default(EntityRef<state>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cityId
		{
			get
			{
				return this._cityId;
			}
			set
			{
				if ((this._cityId != value))
				{
					this.OncityIdChanging(value);
					this.SendPropertyChanging();
					this._cityId = value;
					this.SendPropertyChanged("cityId");
					this.OncityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cityName
		{
			get
			{
				return this._cityName;
			}
			set
			{
				if ((this._cityName != value))
				{
					this.OncityNameChanging(value);
					this.SendPropertyChanging();
					this._cityName = value;
					this.SendPropertyChanged("cityName");
					this.OncityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", DbType="Int NOT NULL")]
		public int stateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				if ((this._stateId != value))
				{
					if (this._state.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstateIdChanging(value);
					this.SendPropertyChanging();
					this._stateId = value;
					this.SendPropertyChanged("stateId");
					this.OnstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="city_admission", Storage="_admissions", ThisKey="cityId", OtherKey="cityId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_city", Storage="_state", ThisKey="stateId", OtherKey="stateId", IsForeignKey=true)]
		public state state
		{
			get
			{
				return this._state.Entity;
			}
			set
			{
				state previousValue = this._state.Entity;
				if (((previousValue != value) 
							|| (this._state.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._state.Entity = null;
						previousValue.cities.Remove(this);
					}
					this._state.Entity = value;
					if ((value != null))
					{
						value.cities.Add(this);
						this._stateId = value.stateId;
					}
					else
					{
						this._stateId = default(int);
					}
					this.SendPropertyChanged("state");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.city = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.city = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.classes")]
	public partial class @class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _classId;
		
		private string _className;
		
		private byte _status;
		
		private EntitySet<section> _sections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassIdChanging(int value);
    partial void OnclassIdChanged();
    partial void OnclassNameChanging(string value);
    partial void OnclassNameChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public @class()
		{
			this._sections = new EntitySet<section>(new Action<section>(this.attach_sections), new Action<section>(this.detach_sections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int classId
		{
			get
			{
				return this._classId;
			}
			set
			{
				if ((this._classId != value))
				{
					this.OnclassIdChanging(value);
					this.SendPropertyChanging();
					this._classId = value;
					this.SendPropertyChanged("classId");
					this.OnclassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_className", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string className
		{
			get
			{
				return this._className;
			}
			set
			{
				if ((this._className != value))
				{
					this.OnclassNameChanging(value);
					this.SendPropertyChanging();
					this._className = value;
					this.SendPropertyChanged("className");
					this.OnclassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_section", Storage="_sections", ThisKey="classId", OtherKey="classId")]
		public EntitySet<section> sections
		{
			get
			{
				return this._sections;
			}
			set
			{
				this._sections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.@class = this;
		}
		
		private void detach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.@class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gender")]
	public partial class gender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _genderId;
		
		private string _genderName;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngenderIdChanging(int value);
    partial void OngenderIdChanged();
    partial void OngenderNameChanging(string value);
    partial void OngenderNameChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public gender()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int genderId
		{
			get
			{
				return this._genderId;
			}
			set
			{
				if ((this._genderId != value))
				{
					this.OngenderIdChanging(value);
					this.SendPropertyChanging();
					this._genderId = value;
					this.SendPropertyChanged("genderId");
					this.OngenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string genderName
		{
			get
			{
				return this._genderName;
			}
			set
			{
				if ((this._genderName != value))
				{
					this.OngenderNameChanging(value);
					this.SendPropertyChanging();
					this._genderName = value;
					this.SendPropertyChanged("genderName");
					this.OngenderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gender_admission", Storage="_admissions", ThisKey="genderId", OtherKey="GenderId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.gender = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.gender = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nationality")]
	public partial class nationality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nationalityId;
		
		private string _nationality1;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnationalityIdChanging(int value);
    partial void OnnationalityIdChanged();
    partial void Onnationality1Changing(string value);
    partial void Onnationality1Changed();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public nationality()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationalityId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nationalityId
		{
			get
			{
				return this._nationalityId;
			}
			set
			{
				if ((this._nationalityId != value))
				{
					this.OnnationalityIdChanging(value);
					this.SendPropertyChanging();
					this._nationalityId = value;
					this.SendPropertyChanged("nationalityId");
					this.OnnationalityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nationality", Storage="_nationality1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nationality1
		{
			get
			{
				return this._nationality1;
			}
			set
			{
				if ((this._nationality1 != value))
				{
					this.Onnationality1Changing(value);
					this.SendPropertyChanging();
					this._nationality1 = value;
					this.SendPropertyChanged("nationality1");
					this.Onnationality1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nationality_admission", Storage="_admissions", ThisKey="nationalityId", OtherKey="nationality")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.nationality1 = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.nationality1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section")]
	public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sectionId;
		
		private string _sectionName;
		
		private int _classId;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
		private EntityRef<@class> _class;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsectionIdChanging(int value);
    partial void OnsectionIdChanged();
    partial void OnsectionNameChanging(string value);
    partial void OnsectionNameChanged();
    partial void OnclassIdChanging(int value);
    partial void OnclassIdChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public section()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			this._class = default(EntityRef<@class>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sectionId
		{
			get
			{
				return this._sectionId;
			}
			set
			{
				if ((this._sectionId != value))
				{
					this.OnsectionIdChanging(value);
					this.SendPropertyChanging();
					this._sectionId = value;
					this.SendPropertyChanged("sectionId");
					this.OnsectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sectionName
		{
			get
			{
				return this._sectionName;
			}
			set
			{
				if ((this._sectionName != value))
				{
					this.OnsectionNameChanging(value);
					this.SendPropertyChanging();
					this._sectionName = value;
					this.SendPropertyChanged("sectionName");
					this.OnsectionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classId", DbType="Int NOT NULL")]
		public int classId
		{
			get
			{
				return this._classId;
			}
			set
			{
				if ((this._classId != value))
				{
					if (this._class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclassIdChanging(value);
					this.SendPropertyChanging();
					this._classId = value;
					this.SendPropertyChanged("classId");
					this.OnclassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="section_admission", Storage="_admissions", ThisKey="sectionId", OtherKey="sectionId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_section", Storage="_class", ThisKey="classId", OtherKey="classId", IsForeignKey=true)]
		public @class @class
		{
			get
			{
				return this._class.Entity;
			}
			set
			{
				@class previousValue = this._class.Entity;
				if (((previousValue != value) 
							|| (this._class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._class.Entity = null;
						previousValue.sections.Remove(this);
					}
					this._class.Entity = value;
					if ((value != null))
					{
						value.sections.Add(this);
						this._classId = value.classId;
					}
					else
					{
						this._classId = default(int);
					}
					this.SendPropertyChanged("@class");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.section = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.section = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.session")]
	public partial class session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sessionId;
		
		private string _sessionName;
		
		private System.DateTime _startFrom;
		
		private System.DateTime _endFrom;
		
		private byte _status;
		
		private EntitySet<admission> _admissions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsessionIdChanging(int value);
    partial void OnsessionIdChanged();
    partial void OnsessionNameChanging(string value);
    partial void OnsessionNameChanged();
    partial void OnstartFromChanging(System.DateTime value);
    partial void OnstartFromChanged();
    partial void OnendFromChanging(System.DateTime value);
    partial void OnendFromChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public session()
		{
			this._admissions = new EntitySet<admission>(new Action<admission>(this.attach_admissions), new Action<admission>(this.detach_admissions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				if ((this._sessionId != value))
				{
					this.OnsessionIdChanging(value);
					this.SendPropertyChanging();
					this._sessionId = value;
					this.SendPropertyChanged("sessionId");
					this.OnsessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string sessionName
		{
			get
			{
				return this._sessionName;
			}
			set
			{
				if ((this._sessionName != value))
				{
					this.OnsessionNameChanging(value);
					this.SendPropertyChanging();
					this._sessionName = value;
					this.SendPropertyChanged("sessionName");
					this.OnsessionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startFrom", DbType="Date NOT NULL")]
		public System.DateTime startFrom
		{
			get
			{
				return this._startFrom;
			}
			set
			{
				if ((this._startFrom != value))
				{
					this.OnstartFromChanging(value);
					this.SendPropertyChanging();
					this._startFrom = value;
					this.SendPropertyChanged("startFrom");
					this.OnstartFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endFrom", DbType="Date NOT NULL")]
		public System.DateTime endFrom
		{
			get
			{
				return this._endFrom;
			}
			set
			{
				if ((this._endFrom != value))
				{
					this.OnendFromChanging(value);
					this.SendPropertyChanging();
					this._endFrom = value;
					this.SendPropertyChanged("endFrom");
					this.OnendFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="session_admission", Storage="_admissions", ThisKey="sessionId", OtherKey="sessionId")]
		public EntitySet<admission> admissions
		{
			get
			{
				return this._admissions;
			}
			set
			{
				this._admissions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.session = this;
		}
		
		private void detach_admissions(admission entity)
		{
			this.SendPropertyChanging();
			entity.session = null;
		}
	}
}
#pragma warning restore 1591
